#!/bin/bash

TEMP=/tmp/current_wall

files=(~/.config/hypr/wallpapers/*)

scripts=~/.config/hypr/scripts

cooldown=1

change () {
    index=$(cat $TEMP)
    index=$((index+$1))
    if [ $index -ge ${#files[@]} ]; then
        index=0
    fi
    echo $index > $TEMP
    swww img "${files[$index]}" --transition-fps 60 --transition-type grow --transition-pos 0.925,0.977 --transition-duration 1
    exit 0
}
while true
do
    case "$1" in
        "cycle")
            change 1
            ;;
        "cycler")
            change -1
            ;;
        "arrow-icon")
            if ~/.config/hypr/scripts/toolbar_state; then
                echo '{"text":"","tooltip":"Collapse"}'
            else
                echo '{"text":"","tooltip":"Expand"}'
            fi
            ;;
        "ss-icon")
            if ~/.config/hypr/scripts/toolbar_state; then
                echo '{"text":"","tooltip":"Screenshot"}'
            else
                echo ""
            fi
            ;;
        "weather")
            if ~/.config/hypr/scripts/toolbar_state; then
                ~/.scripts/wttr
            else
                echo ""
            fi
            ;;
        "wall")
            if ~/.config/hypr/scripts/toolbar_state; then
                echo '{"text":" ","tooltip":"Wallpaper Next | Prev"}'
            else
                echo ""
            fi
            ;;
        "power")
            if ~/.config/hypr/scripts/toolbar_state; then
                echo '{"text":"⏻","tooltip":"Power"}'
            else
                echo ""
            fi
            ;;
        "clipboard")
            if ~/.config/hypr/scripts/toolbar_state; then
                echo '{"text":"","tooltip":"Clipboard | Nuke | Delete"}'
            else
                echo ""
            fi
            ;;
    esac
    sleep $cooldown
done

