#!/bin/bash

TEMP=/tmp/current_wall

files=(~/.config/hypr/wallpapers/)

cooldown=1

change () {
    index=$(cat $TEMP)
    index=$((index+$1))
    if [ $index -ge $(ls $files | wc -l) ]; then
        index=0
    elif [ $index -lt 0 ]; then
        index=$(($(ls $files | wc -l)-1))
    fi
    echo $index > $TEMP
    swww img "$files/$index" --transition-fps 60 --transition-type grow --transition-pos 0.925,0.977 --transition-duration 1
    exit 0
}
while true
do
    case "$1" in
        "cycle")
            change 1
            ;;
        "cycler")
            change -1
            ;;
    esac
    sleep $cooldown
done

